name: Update Microsoft Learn Stats

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:

permissions:
  contents: write   # ✅ allow pushing to repo

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # ✅ use built-in token with write perms

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml matplotlib

      - name: Run scraper
        run: python .github/scripts/update_learn.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md learn_stats.png
          git diff-index --quiet HEAD || git commit -m "Update Microsoft Learn stats"
          git push
